version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ignite-call-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ignitecall
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data